language: java
jdk:
  - openjdk8

# Travis CI 를 어느 브랜치에 push 될 때 수행할 시 설정
branches:
 only:
    - master

before_script:
  - cd springboot/study_springboot_jeonka/
  - pwd

#Travis CI 서버의 home
cahce:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_deploy:
 - cd ..
 - zip -r freelec-springboot2-webservice.zip study_springboot_jeonka
 - mkdir -p deploy
 - mv freelec-springboot2-webservice.zip deploy/freelec-springboot2-webservice.zip

deploy:
 - provider: s3
   access_key_id: $AWS_ACCESS_KEY
   secret_access_key: $AWS_SECRET_KEY
   bucket: jeonka-build
   region: ap-northeast-2
   skip_cleanup: true
   acl: private
   local_dir: deploy
   wait-until-deployed: true

notifications:
 email:
  recipients:
   - ruddks2008@naver.com
