language: java
jdk:
  - openjdk8

# Travis CI 를 어느 브랜치에 push 될 때 수행할 시 설정
branches:
 only:
    - main

before_script:
  - "cd springboot/study_springboot_jeonka/"
  - "pwd"

before_install:
  - "chmod +x gradlew"

#Travis CI 서버의 home
cahce:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script:
  - "cd springboot/study_springboot_jeonka/"
  - "pwd"
  - "./gradlew clean build"

## CI 실행 완료 시 메일로 알람
#notifications:
#  email:
#    recipients:
#      - ruddks2009@naver.com
